// <auto-generated />
namespace WinStatus.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Primary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Primary));
        
        string IMigrationMetadata.Id
        {
            get { return "201804062310145_Primary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
